### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by slewsalesforce** [forcedotcom/sfdx-scanner#1006]
**Describe the bug**
When I run the command to scan the code, the terminal shows me this error message : TypeError: Cannot read properties of undefined (reading 'prototype')

**To Reproduce**
I was just following the help article, running commands such as  : 
sfdx scanner:run --format csv --target "./classes/ChangePasswordController.cls"
sfdx scanner:run -f csv -t "./classes/*.cls"
but nothing works

**Expected behavior**
The command should return the scan result.

**Screenshots**
<img width="678" alt="Screenshot 2023-03-07 at 9 42 33 AM" src="https://user-images.githubusercontent.com/87812604/223297442-800a131d-fe37-42d2-a8c9-15b0c4f24b0b.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2.1
 - Scanner Version 3.10.0
 - Java 19
 - CLI 7.190.2

"Workaround": I have reinstalled  code analyzer but still couldn't work

"Urgency":  "Not business-stopping"

**Comment by jfeingold35** [comment]
Hi @slewsalesforce . We're going to need a bit more info to try and narrow this down, because we're unable to reproduce.
- Does this happen with all engines, or just one engine in particular? You can figure that out by using the `--engine` flag.
- Does this happen for other files in the directory, or just that one?
- Have you made any changes to your `Config.json`, such as new target patterns?
- Are you using any custom rulesets for PMD?

**Comment by jfeingold35** [comment]
@azanatta , can you please provide the information requested above?
> * Does this happen with all engines, or just one engine in particular? You can figure that out by using the `--engine` flag.
> * Does this happen for other files in the directory, or just that one?
> * Have you made any changes to your `Config.json`, such as new target patterns?
> * Are you using any custom rulesets for PMD?

**Comment by jfeingold35** [comment]
Customer unresponsive; closing issue.
