### ISSUE TITLE
Getting 'sourceCode.getScope is not a function' during js file validation

### ISSUE THREAD

**Issue by KamilaCieslinska** [forcedotcom/sfdx-scanner#1102]
**Describe the bug**
When we trying to make eslint verification for one js file using sfdx scanner, we got an error:

```
sfdx scanner:run -t \file.js --engine "eslint" --eslintconfig ".eslintrc.json" -o codescan/eslint-scan.csv -f csv -s 3

**ERROR running scanner:run:  sourceCode.getScope is not a function
Occurred while linting \file.js:1
Rule: "unicorn/import-style"**
```

**To Reproduce**
We're using that command for specific js file:
`sfdx scanner:run -t \file.js --engine "eslint" --eslintconfig ".eslintrc.json" -o codescan/eslint-scan.csv -f csv -s 3`

**Expected behavior**
I expect verification message, but I got error 

**Desktop (please complete the following information):**
 - Windows 11 Enterprise
 - Scanner Version v3.13.0
 - sfdx-cli/7.206.6  node-v18.15.0
 

**Additional context**
When I use just eslint for verification, it works as expected:
command which I used: `node node_modules\eslint\bin\eslint.js \file.js `
but when I want to use it with sfdx scanner it doesn't work. 

"Workaround": Have you found any ways to sidestep the problem? No

**Comment by jfeingold35** [comment]
@KamilaCieslinska , it sounds like you're using a custom configuration of ESLint, correct? If so, could you please post your `.eslintrc.json` file?

**Comment by KamilaCieslinska** [comment]
Yes, sure. Here you can find file which I use
`
{
  "plugins": ["jsdoc"],
  "extends": ["plugin:jsdoc/recommended", "prettier"],
  "overrides": [
    {
      "files": ["**/aura/**/*.js"],
      "plugins": ["@salesforce/eslint-plugin-aura"],
      "extends": [
        "plugin:@salesforce/eslint-plugin-aura/recommended",
        "plugin:@salesforce/eslint-plugin-aura/locker"
      ]
    },
    {
      "files": ["**/lwc/**/*.js"],
      "plugins": ["@lwc/eslint-plugin-lwc"],
      "extends": [
        "@salesforce/eslint-config-lwc/recommended",
        "plugin:unicorn/recommended"
      ],
      "rules": {
        "@lwc/lwc/no-unexpected-wire-adapter-usages": "off",
        "unicorn/prevent-abbreviations": "off",
        "unicorn/filename-case": "off",
        "unicorn/prefer-dom-node-append": "off",
        "unicorn/no-null": "off",
        "no-var": "error",
        "prefer-const": "error",
        "prefer-destructuring": "off"
      }
    },
    {
      "files": ["*.test.js"]
    }
  ],
  "rules": {
    "jsdoc/no-undefined-types": "off",
    "jsdoc/require-jsdoc": [
      2,
      {
        "require": {
          "FunctionDeclaration": true,
          "MethodDefinition": true,
          "ClassDeclaration": false
        }
      }
    ],
    "func-names": "off",
    "vars-on-top": "off",
    "no-unused-expressions": "off"
  }
}
`

**Comment by jfeingold35** [comment]
@KamilaCieslinska , thanks! I'll try to reproduce this and get back to you if I have any additional questions or information to provide.

**Comment by jfeingold35** [comment]
@KamilaCieslinska , I'm unable to reproduce the issue with just this information. A few follow-up questions:
1. Does ESLint work correctly if you invoke it via `npx`, (i.e., `npx eslint \file.js`)?
2. Are you doing any additional configuration of ESLint via `package.json` or some other config file?
3. Is line 1 of the file an import/require statement? If so, what type of statement is it?

**Comment by KamilaCieslinska** [comment]
1. Yes, it works as expected
2. No
3. In this case it is 
`import { LightningElement, api } from "lwc";`

**Comment by jfeingold35** [comment]
@KamilaCieslinska , I think there's some detail about your setup that I'm missing, because I'm running into some problems attempting to reproduce this.

The first problem is that the config you provided limits the unicorn rules to files whose path matches `**/lwc/**/*.js`, so I'm not sure how `unicorn/import-style` is even running against `file.js`.
- Are you _positive_ there's no `.eslintrc` file with a `.js`, `.cjs`, `.yaml`, or `.yml` extension anywhere in your repo, nor an `eslintConfig` property on your `package.json`?
    - Do any of those files exist in a parent directory of the current directory?
- Does the path to `file.js` somehow include an `lwc` folder that's not being shown here?
    - Are you running the command from the root of your project, or from a subfolder?

However, even if I put the import statement you provided in line 1 of a file named `src/lwc/file.js`, I still can't reproduce.
- Does the error happen for every file in the project, every file in the directory, or just the one file?
    - If just the one file, does commenting out everything except the import statement resolve the issue?
- If you have any coworkers with a Unix machine, can they reproduce this, or is it just on a Windows machine?

Thanks for your patience. Hopefully we can get this sorted out soon.

**Comment by KamilaCieslinska** [comment]
Hello,
generally \file.js was an example. The full path to my component is more complex, but I just want to show that eslint works correctly for one file, but with scanner not (with the same file).

Additionally:
- don't have any additional configuration
- the full path to my file is for example: lwc/accordion/accordion.js
- I'm running the command from the root
- the error happen for every .js file in the project (each components)
- I don't know about Unix machine but generally some coworkers can reproduce it on theirs Windows machine. We compared the configuration - we have the same.

**Comment by jfeingold35** [comment]
@KamilaCieslinska , thanks for clarifying.
Could you please do the following?
- Create a component whose `.js` file contains nothing but the single statement `import { LightningElement, api } from "lwc";` and let me know whether the error occurs even in this file. This will indicate whether the problem is related to the contents of the file.
- Post the `dependencies`, `devDependencies`, and `resolutions` properties of your `package.json`, and attach your `yarn.lock` or `package-lock.json` files. That way, I can recreate your exact setup as closely as possible.

Thanks!

**Comment by KamilaCieslinska** [comment]
Hello,
I created new, empty component, but the same error appeared.

Regarding dependencies:

`"dependencies": {
    "@lwc/eslint-plugin-lwc": "^1.6.2",
    "@prettier/plugin-xml": "^2.2.0",
    "@salesforce/eslint-config-lwc": "^3.4.0",
    "@salesforce/eslint-plugin-aura": "^2.1.0",
    "@salesforce/eslint-plugin-lightning": "^1.0.0",
    "eslint": "^8.41.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-jest": "^27.2.1",
    "eslint-plugin-jsdoc": "^46.1.0",
    "eslint-plugin-unicorn": "^47.0.0",
    "htmlhint": "^1.1.4",
    "prettier": "^2.8.8",
    "prettier-plugin-apex": "1.13.0",
    "stylelint": "^15.6.2",
    "stylelint-config-standard": "^33.0.0",
    "stylelint-declaration-strict-value": "^1.9.2",
    "stylelint-prettier": "^3.0.0"
  },
  "devDependencies": {
    "@salesforce/sfdx-lwc-jest": "^1.3.0",
    "lint-staged": "^13.2.2",
    "parse-git-numstat": "^1.1.2",
    "xml-js": "^1.6.11"
  },`

package.lock file attached.
[package-lock.txt](https://github.com/forcedotcom/sfdx-scanner/files/12002269/package-lock.txt)

**Comment by jfeingold35** [comment]
@KamilaCieslinska , I'm still struggling to reproduce this. My current theory is that it may be unique to Windows machines, and I'm in the process of testing that theory. I'll keep you posted as more information becomes available or if I need further clarification.
Thanks for your petience.

**Comment by jfeingold35** [comment]
@KamilaCieslinska , quick question: When you run `node -v`, what result do you get?

**Comment by KamilaCieslinska** [comment]
Result of command is: v18.16.1

**Comment by KamilaCieslinska** [comment]
Any updates? :) still have the same error

**Comment by jfeingold35** [comment]
@KamilaCieslinska , sorry for the delay. The team is very short-staffed at the moment, and I've been struggling to find time to work on this.
I appreciate your patience, and I'll try to get some kind of update for you regarding this in the near future.

**Comment by jfeingold35** [comment]
@KamilaCieslinska , unfortunately, I'm still unable to reproduce this, even on a Windows machine. My method for attempting this has been as follows:
1. I've installed `sfdx-scanner` on a Windows machine.
2. I've created a project using the `package.json` properties and `package-lock.json` file that you posted.
3. Since you've said this happens in any file, I've used [the apiMethod component from the LWC recipes repo](https://github.com/trailheadapps/lwc-recipes/tree/main/force-app/main/default/lwc/apiMethod) as a sample component.
4. I've run `sfdx scanner:run --engine "eslint" --format csv --eslintconfig ".eslintrc.json" --target "./src/lwc/apiMethod/apiMethod.js"` from the root of the project.

Based on what you've told me, this should be enough to reproduce the issue, and yet I'm not seeing anything.

So at this point I think we've got two options for how to proceed.

The first option is for me to attempt to replicate your set-up even more accurately in the hopes of reproducing the error on my end.
- If your repo is public-facing, you can post a link and indicate a specific file that causes the error, and I can clone the repo directly and run against that file.
- Alternatively, you could create a second project with the same `package.json` (minus any particularly sensitive information), `.eslintrc.json`, and `package-lock.json`, as well as one or two simple LWC components that you've verified cause the error (to avoid posting sensitive information, you could consider using [one of the sample recipes here](https://github.com/trailheadapps/lwc-recipes/tree/main/force-app/main/default/lwc)). If you post that project as a `.zip`, I can download that and use it locally.

The second option would be for you to do some more debugging on your end and come back to me with your findings so we have more to go on. The following questions are of special interest here.
- If you delete your `node_modules` folder and `package-lock.json` file and then run `npm install` again, does that fix the problem?
- You've said you're not sure whether any of your coworkers with Unix machines can reproduce this. Could you look further into that?
- You've also said you have _some_ coworkers who can reproduce it on their Windows machines. Does this mean there are other coworkers who _can't_ reproduce it on their Windows machines? If so, how do their configurations differ from yours?
    - Are they on a different version of Windows than you?
    - Do they get different results for `sfdx -v`, `node -v`, or `npx eslint -v` than you do?
    - Are your `package-lock.json` files the same?
    - Do you have the same modules installed? (i.e, do you get the same results for `npm ls --all`?)
    - Are they targeting different files than you, or the same ones?
    - Are they running the exact same command as you, or are they inputting it differently in any way?

Let me know which of these options you prefer, and we can proceed accordingly.

**Comment by KamilaCieslinska** [comment]
Hello,

Repo is not public so you cannot clone it. Let's go with the second option and here you can find answers for your questions:
-  removing `node_modules` folder and `package-lock.json` file, then run `nmp install `again - it doesn't help
- I have no possibility to check it with Unix machine
- I checked with another team member who has the same problem on his own. You can find our result into attachment
- regardless of the file, the error message is the same
- the command which we use are the same

As you can see we can find some differences between our configuration, but still also me and my team member has the same issue.

[command_results.pdf](https://github.com/forcedotcom/sfdx-scanner/files/12181863/command_results.pdf)

**Comment by jfeingold35** [comment]
@KamilaCieslinska , this doesn't narrow it down as much as I was hoping it would. There are still too many variables involved in the scenario. D ou have any coworkers on Windows machines who _can't_ reproduce the issue? Because if you have two configurations that can reproduce it and one that can't, that's going to help us exclude a lot of variables and hopefully narrow down some kind of cause.

**Comment by KamilaCieslinska** [comment]
Sure, differences attached.
[commandResults.pdf](https://github.com/forcedotcom/sfdx-scanner/files/12225873/commandResults.pdf)

**Comment by jfeingold35** [comment]
These PDFs are actually pretty hard to work with. Could you please upload the actual files, either individually or as a .zip? Also, I believe the content of the first PDF you posted got mangled somehow, so if you could post those files as well that would help too.

**Comment by KamilaCieslinska** [comment]
Sure, here you can find separate files for SUCCESS and NO SUCCESS (getting error).

[SUCCESS_npm ls --all.txt](https://github.com/forcedotcom/sfdx-scanner/files/12230042/SUCCESS_npm.ls.--all.txt)
[SUCCESS-packagelock.txt](https://github.com/forcedotcom/sfdx-scanner/files/12230045/SUCCESS-packagelock.txt)
[NO_SUCCESS_npm ls --all.txt](https://github.com/forcedotcom/sfdx-scanner/files/12230046/NO_SUCCESS_npm.ls.--all.txt)
[NO_SUCCESS-packagelock .txt](https://github.com/forcedotcom/sfdx-scanner/files/12230047/NO_SUCCESS-packagelock.txt)

**Comment by jfeingold35** [comment]
@KamilaCieslinska , thanks.
These files are identical, which means that there must be some other difference between the two machines. The PDF you sent indicates that both are running the same version of `sfdx`, so that's not the problem. As such, please check the following:
1. The failing machine is listed as running Windows 11 22H2, and the passing machine is listed as running Windows 11 21H2. Is that correct? If so, please indicate which version of Windows 11 is being used by the other teammate who sees the error.
2. Are both machines running the same version of `sfdx-scanner`? This can be checked with `sfdx plugins`.
3. If you uninstall and reinstall the scanner (`sfdx plugins:uninstall @salesforce/sfdx-scanner` then `sfdx plugins:install @salesforce/sfdx-scanner`), does that fix it? Alternatively, if the coworker with a working setup does that, does that break the scanner for them?
4. Are there any other differences between machines here?
4a. Is the code being scanned identical?
4b. Is the command being entered differently?
4c. Is the command being executed from the same relative directory?

Thanks.

**Comment by KamilaCieslinska** [comment]
Thanks for your engagement :) 
Below, you can find all the answers:

1) **FAILING** machine: Windows 11 22H2 (my) and Windows 11 21H2,  **PASSING** machine: Windows 11 21H2
as you can see, Windows is not a problem because Windows 11 21H2 is both a passing machine and a failing machine.

2) Results of `sfdx plugins`:
**FAILING** machine: @salesforce/sfdx-scanner 3.13.0
**PASSING** machine: the same result, @salesforce/sfdx-scanner 3.13.0

3) I'll check it in the middle of the day and let you know.

4) code is identical, command is entered identical (from VS terminal) and is executed from the same relative directory.

**Comment by KamilaCieslinska** [comment]
It seems that the newest version of scanner 3.15 available since August is working properly in our case :) **Yupi!**

I changed the version from 3.13 to 3.15 and did the tests again. Everything works as it should, the error no longer occurs.

Thank you for your commitment! 
**Problem solved for the moment.**
