### ISSUE TITLE
[BUG] Trying to execute PMD XML rule with sfdx-scanner

### ISSUE THREAD

**Issue by allurisriakhil** [forcedotcom/sfdx-scanner#1112]
**Describe the bug**
I wrote a custom pmd xml xpath rule and trying to execute it with sfdx-scanner 

**To Reproduce**
Below is the rule that i am trying to execute. The same rule is working for apex if i change the class to net.sourceforge.pmd.lang.apex.rule.ApexXPathRule and language to "apex". But not working for xml language rule.

```
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="CustomCodeStyle"
         xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <description>Custom ruleset for checking file naming convention starting with SA_</description>
    <rule name="File name should start with SA_ in xml" class="net.sourceforge.pmd.lang.xml.rule.DomXPathRule" language="xml" message="File name should start with SA_ in xml">
        <description>File name should start with SA_</description>
        <priority>3</priority>
        <properties>
          <property name="version" value="2.0"/>
          <property name="xpath">
            <value>
              <![CDATA[ /*[starts-with(pmd:fileName(), 'SA_')]  ]]>
            </value>
          </property>
        </properties>
        <example>
        <![CDATA[
          <file name="SA_MyClass.xml">...</file> <!-- this is correct -->
          <file name="MyClass.xml">...</file> <!-- this is incorrect -->
        ]]>
       </example>
    </rule>
</ruleset>
```

Commands used to add the rule:

`sfdx scanner:rule:add --language xml --path  rules/category/xml/sa_new_rule.xml`

**Expected behavior**
This rule should identify the .xml file names that starts with 'SA_'

**Desktop (please complete the following information):**
 - OS: 13.4.1
 - Scanner Version 3.11.0

**Comment by allurisriakhil** [comment]
Hi @jfeingold35, This issue is in reference to ticket no:https://github.com/forcedotcom/sfdx-scanner/issues/1053

**Comment by allurisriakhil** [comment]
@jfeingold35, may i know if we are able to run pmd xml rules using the scanner? Because the same rule is working with apex language I even didn't changed the xpath expression but it is not working with xml language.

**Comment by jfeingold35** [comment]
@allurisriakhil , yes, you can run PMD rules against XML files, though [as explained elsewhere](https://github.com/forcedotcom/sfdx-scanner/issues/992#issuecomment-1452105622), in order to target `*-meta.xml` files, you'll need to remove the `!**/*-meta.xml` entry from PMD's `targetPatterns` array in `~/.sfdx-scanner/Config.json`.

By replacing your rule's CDATA expression with the one from PMD's built-in rule [MistypedCDATASection](https://github.com/pmd/pmd/blob/pmd_releases/6.55.0/pmd-xml/src/main/resources/category/xml/errorprone.xml#L26) and adding it with `scanner:rule:add`, I'm able to produce a violation in an XML file containing the CDATA expression `<![CDATA[[ character data ]]>`.

I understand your frustration, but it seems like the most likely possibility here is that there's either a bug in your rule or a bug in PMD itself. Either way, your best bet is to reach out to PMD directly, as they'll be most equipped to help you resolve the issue.

**Comment by allurisriakhil** [comment]
@jfeingold35 thanks for answering the issue is with the *-meta.xml files it got resolved after the solution you provided yesterday. Once again thanks for your time and support.
