### ISSUE TITLE
[BUG] Method-level targeting isn't supported with this command.

### ISSUE THREAD

**Issue by allurisriakhil** [forcedotcom/sfdx-scanner#1139]
**Describe the bug**
I am trying to execute sfdx scanner:run command with the target but it is throwing the error 
ERROR running scanner:run:  The target 'target/path' is invalid because method-level targeting isn't supported with this command.

**Desktop (please complete the following information):**
 - OS: mac-os 13.4.1 
 - Scanner Version 3.11.0

**Comment by allurisriakhil** [comment]
Hi @jfeingold35, Please find the command below

`sfdx scanner:run --format csv --target "Execute/Scan/\!PastReleases/v0/v0.1-#1-report_1.html" --outfile=Scan.csv`

Above i am using backslash `\!` to pass the `!`

**Comment by jfeingold35** [comment]
@allurisriakhil , `scanner:run;dfa` uses the `#` character for method-level targeting. E.g., `--target "./path/to/someFile.cls#methodOfInterest"`. `scanner:run` is identifying the presence of the `#` character in the target and throwing an error, because it thinks this is an attempt to do a method-level target.
For this reason, we recommend against using the `#` character in your file name, if you can avoid it.

**Comment by allurisriakhil** [comment]
@jfeingold35, Thanks for the clarification is there any supporting documentation for the same to see what characters are allowed in the target? 

And if we want to still use the `#` character in our file name is there any work around?

**Comment by jfeingold35** [comment]
We don't have any official documentation about unsupported characters at this time, though we can look into adding some.
In the meantime, we recommend that you avoid using either the `#` character or glob wildcard characters (`!*()[]{}`) in the names of files or directories you wish to target directly via the `--target` flag, as the former collides with our method-level targeting solution and the latter have been observed to cause problems with `globby`, the library we use for glob matching (see Issue #952).

As for workarounds, that depends on what you're trying to do. 
1. In this specific example, it looks like you're trying to scan every file in `execute/scan` _except_ for this specific file that resides in `pastreleases/v0`. If so, then unless you've enabled PMD's HTML rules, there are no engines that target HTML files, so you should be able to simply omit the file from the target path entirely and it will be ignored by default.
2. In the more general case where you're trying to exclude a file with an unsupported character that would otherwise be scanned, you can add an exclusion pattern to the relevant engines' `targetPatterns` arrays in `~/.sfdx-scanner/Config.json`.
3. If you want to _include_ a file/directory that has unsupported characters in the name, your best bet is to target the directory containing that file/directory instead (e.g., `--target ./mydirectory` instead of `--target ./mydirectory/fileWith#InTheName.cls`).

**Comment by allurisriakhil** [comment]
@jfeingold35 , Thanks for the clarification. But in the documentation (ref: https://forcedotcom.github.io/sfdx-scanner/en/v3.x/scanner-commands/run/ ) provided online it is mentioned as below could you please let me know what glob patterns can be used/allowed here?

-t, --target=_target_
 (required) Source code location. **May use glob patterns**. Specify multiple values as a comma-separated list.

**Comment by jfeingold35** [comment]
@allurisriakhil , I'm not sure I understand the question. The [examples](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/scanner-commands/run/#example) section on that page has examples of using globs as values for `--target`. We use [`globby`](https://www.npmjs.com/package/globby) to parse globs, so we should support the syntax they do.
The problem is that if you use glob wildcard characters in the name of your file, then that gets mistaken for a glob, and it will attempt to resolve that glob instead of just scanning the file.

**Comment by allurisriakhil** [comment]
@jfeingold35, understood now thanks for the clarification once again.

**Comment by jfeingold35** [comment]
@allurisriakhil , glad to hear it. Do I have your permission to close this issue?

**Comment by allurisriakhil** [comment]
@jfeingold35, yes please.
