### ISSUE TITLE
[BUG] LimitReached / InternalExecutionError when have @AuraEnabled on an Apex Method

### ISSUE THREAD

**Issue by shivam-rajput123** [forcedotcom/sfdx-scanner#1356]
Hi,
"I am using the following sfdx command to generate a code analyzer DFA report for the security review process.
I hit an error java.lag Out of memory error due to java heap size.

sfdx scanner:run:dfa --sfgejvmargs "-Xmx256m" --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./"
--category="Security"  --pathexplimit=-1

**Comment by rmohan20** [comment]
Hi @shivam-rajput123 - thanks for checking with us.
This is working as designed. Your project code probably needs more heap space than 256M. I would also remove the `--pathexplimit` from the command so that individual entry points that hit this limit will not stop the analysis.

Can you try something like this where we assign 5G heap space? You could increase or decrease it depending on you machine's capabilities:

```
sfdx scanner:run:dfa --sfgejvmargs "-Xmx5G" --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"
```

Once the above command reaches completion, you could tweak the run for specific method entry points that hit the Path Expansion Limit and run with `--pathexplimit -1` [as described in our documentation](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/working-with-sfge/#understand-limitreached-errors).

I'm closing this issue for now - feel free to reopen if you have more questions. Thanks.

**Comment by shivam-rajput123** [comment]
@rmohan20 Thanks I will check it.
