### ISSUE TITLE
[BUG] 0 violations across 0 files

### ISSUE THREAD

**Issue by EmirMalikov** [forcedotcom/sfdx-scanner#1363]
after using 
            sf scanner run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"
It shows
            Executed pmd, found 0 violation(s) across 0 file(s).
            Executed retire-js, found 0 violation(s) across 0 file(s).
anything i'm doing wrong? There no codes in my project, but anyway appexchange requires code analyzer results

**Comment by johnbelosf** [comment]
This is working as expected - the CSV file will explicitly state when there are no violations so that you can use it as part of your security review submission.

I would also recommend you run the pmd-appexchange set of rules created specifically to help partners prepare for the AppExchange Security Review - https://forcedotcom.github.io/sfdx-scanner/en/v3.x/architecture/pmd-engine/

**Comment by EmirMalikov** [comment]
but this giving me only this 
   "Problem","Severity","File","Line","Column","Rule","Description","URL","Category","Engine"
Is it okay? is it correct way to submit

**Comment by jfeingold35** [comment]
@EmirMalikov , yeah, you're fine.
