### ISSUE TITLE
[BUG] LimitReached / InternalExecutionError

### ISSUE THREAD

**Issue by shivam-rajput123** [forcedotcom/sfdx-scanner#1367]
Hi,
"I am using the following sfdx command to generate a code analyzer DFA report for the security review process.
I hit an error java.lag Out of memory error due to java heap size.

sfdx scanner:run:dfa --sfgejvmargs "-Xmx20G" --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./"
--category="Security" --rule-thread-count 2 --rule-thread-timeout 300000

Error showing: Graph Engine reached the path expansion upper limit (1472). The analysis preemptively stopped running on this path to prevent an OutOfMemory error. Rerun Graph Engine and target this entry method with a larger heap space.

**Comment by rmohan20** [comment]
@shivam-rajput123 20G seems like an ample heap space to work with. As mentioned in my [older response](https://github.com/forcedotcom/sfdx-scanner/issues/1356#issuecomment-1945154302), you can (in most cases) reach completion when you target a specific source method and pass in `--pathexplimit -1`. Also, a single thread would be more effective (`--rule-thread-count 1`).

**How do we find specific methods to target?**
OutOfMemory error runs should return an output of violation results created until it errored out. `CodeAnalyzerDFA.csv` in your case (please let us know if it doesn't get created). In the file, you should see some rows with Limit reached error. Use the value in the source method and the file to construct the target parameter. It should look something like this: `--target /path/to/a/source/file#optionalSpecificEntryMethod`. Make sure the `--outfile` names in these supplemental runs are different from the first run so that the original file is not overwritten.

This process needs to be performed for each row that encountered the Limit Reached error.

We are working on making this easier for users, but until then, this is the recommended workaround. I'm closing this issue since this is working as designed, but please feel free to reopen it if you are still blocked. Thanks.
