### ISSUE TITLE
How to disable some of the default PMD rules that come with salesforce code analyser installation?

### ISSUE THREAD

**Issue by kirankapila** [forcedotcom/sfdx-scanner#1597]
### Discussed in https://github.com/forcedotcom/sfdx-scanner/discussions/1583

<div type='discussions-op-text'>

<sup>Originally posted by **kirankapila** August 22, 2024</sup>
Hi Team,

I need to exclude some of the default PMD rules that are available with salesforce code analyser. 

I could see that most rules are spit our at runtime as .xml file from within .jar files.

Is there a better way of disabling a subset of the default PMD rules instead of meddling with .jar files? Please advise

Thanks </div>

**Comment by stephen-carter-at-sf** [comment]
You can submit your own ruleset file with the --pmdconfig flag (see https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/run.html).

If you are unfamiliar with rulesets, see https://pmd.github.io/pmd/pmd_userdocs_making_rulesets.html

Note that in the next few month's you'll us start making available an alpha version of Code Analyzer 5.x which will soon have the PMD engine added in... that will allow you to far more elegantly select rules and run just the ones you want (tagging them to create "playlists", etc). So stay tuned because your exact use case will be far easier in the near future. Until then, with 4.x you'll needt o pass in a ruleset file using the --pmdconfig flag that contains references to just the rules that you want to run.
