### ISSUE TITLE
Not able to upgrade the code analyzer 5

### ISSUE THREAD

**Issue by rajnimtr** [forcedotcom/sfdx-scanner#1657]
### Need/Problem Description

Getting the below error while trying to upgrade using "npm i @salesforce/plugin-code-analyzer"

# npm audit report

micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix`
node_modules/@salesforce/plugin-code-analyzer/node_modules/micromatch

path-to-regexp  4.0.0 - 6.2.2
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix available via `npm audit fix`
node_modules/@salesforce/plugin-code-analyzer/node_modules/path-to-regexp

2 vulnerabilities (1 moderate, 1 high)

### Describe your Desired Solution

I should be able to upgrade the code analyzer to version 5. 

### Urgency

Moderate

**Comment by stephen-carter-at-sf** [comment]
You are doing 2 things that we recommend you don't do.

First
* You are attemping to install the plugin manually. You should be using `sf plugins install ...` and not `npm install ...`

Second
* You are grabbing the wrong version. We haven't marked @salesforce/plugin-code-analyzer with the latest tag because it is still alpha. So you should have done @salesforce/plugin-code-analyzer@latest-alpha

All that to say I recommend you install the `sf` cli and then do what our documentation says:
https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/version-5-setup.html
```
sf plugins install code-analyzer@latest-alpha
```

**Comment by stephen-carter-at-sf** [comment]
Also - please don't add labels to issues.

**Comment by rajnimtr** [comment]
sf plugins install ...  is not working for me. npm install ... still progresess

**Comment by rajnimtr** [comment]
(node:29844) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
    RequestError: unable to get local issuer certificate
    Code: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

**Comment by rajnimtr** [comment]
sf cli is installed

**Comment by rajnimtr** [comment]
@salesforce/cli/2.62.6 win32-x64 node-v20.17.0

**Comment by rajnimtr** [comment]
> Also - please don't add labels to issues.

I did not add any labels. The work item took the default setting

**Comment by stephen-carter-at-sf** [comment]
You may have accidentally done it. Above it says:
> @[rajnimtr](https://github.com/rajnimtr) rajnimtr added the [USER STORY](https://github.com/forcedotcom/sfdx-scanner/labels/USER%20STORY) label [3 hours ago](https://github.com/forcedotcom/sfdx-scanner/issues/1657#event-14789537738)

But regarding your issue... did you try 
```
sf plugins install code-analyzer@latest-alpha
```
instead of using npm directly?

**Comment by stephen-carter-at-sf** [comment]
Maybe your company proxy is getting in the way (as another person was finding over at https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate)

We are unable to reproduce this issue. Maybe you have a home computer you can try instead of a work computer to sanity check?
