### ISSUE TITLE
We are getting error in running one command for salesforce security review 

### ISSUE THREAD

**Issue by agupta-conga** [forcedotcom/sfdx-scanner#1672]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Three files needs to be generated . We are not able to generate third file i.e. CodeAnalyzerPmdAppExchange.csv using following command
sf scanner run --engine pmd-appexchange --format csv --outfile CodeAnalyzerPmdAppExchange.csv --target ./

It is giving following error - 
Parsing --engine 
The flag value "pmd-appexchange" is not in the correct format for "array." Must only contain values in [eslint,eslint-lwc,eslint-typescript,pmd,retire-js,sfge,cpd].

### Steps To Reproduce

Run the command -  sf scanner run --engine pmd-appexchange --format csv --outfile CodeAnalyzerPmdAppExchange.csv --target ./

### Expected Behavior

It should generate all the issues into new file

### Operating System

windows

### Salesforce CLI Version

salesforce/cli/2.10.2 win32-x64 node-v18.15.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

v1.3.0

### Urgency

High

**Comment by stephen-carter-at-sf** [comment]
@agupta-conga you reported that your code analyzer plugin version is v1.3.0 - that is really really old. Are you sure that is correct? 
Please run `sf plugins` and give us the version number that is after `@salesforce/sfdx-scanner` for example 4.7.0 is the latest.

If so, then that would explain why you can't use the pmd-appexchange engine because it didn't exist way back with scanner v1.x.

You must upgrade both sf (since you are running an old version there as well)
```
sf update
```
and the scanner plugin:
```
sf plugins install @salesforce/sfdx-scanner@latest
```

**Comment by agupta-conga** [comment]
Thanks Stephen, I am able to resolve the issue.

Thanks
Astha Gupta


Conga, The Revenue Company
Leave a review
|Support|Community
|
LinkedIn
