### ISSUE TITLE
Feature Request - Async Mode for the CICD purpose

### ISSUE THREAD

**Issue by yasarshaikh** [forcedotcom/sfdx-scanner#169]
Can we have an async mode so that CLI shall proceed further to avoid delay in further execution? 

As of now, the async mode is available for `sfdx force:package:version:create` and `sfdx force:package:install` command. Idea is to have a CICD process somewhat like below - 

1. Engage static code analysis in Async mode
2. Authorize a Dev Hub
3. Create a scratch org 
4. Push the code to the scratch org
5. check static code analysis report(since it took some time, it will be completed by the time) and if the violation percentage crosses a particular threshold, break the pipeline
6. if static code analysis passes the threshold proceed for test classes check. 
7. Check the test classes percentage and depending on the threshold decide to pass the pipeline or not.

**Comment by rmohan20** [comment]
Hi @yasarshaikh - thanks for taking the time to try this plugin and sharing your feedback with us. Appreciate it!

I noticed a couple of themes from your use-case:
1. Running scanner in async mode
2. Evaluating results from scanner and making a decision to break pipeline or not


**Expanding on theme 1:**
Linux and OSX provide the `<command> &` to start a process in the background, and Windows provides `START /B <command>` for the same. Using OS-based capabilities gives us a lot of flexibility to design the CICD flow that best fits our needs.

Here's a simple mockup shell script that triggers the scanner as a background job and later checks for its completion. I've used a sleep to emulate processes we wish to run in the foreground.

```

TARGET_DIR=/my/target/dir
OUTFILE=result1.csv

# Clean up before we begin
if [ -f $OUTFILE ];then
	echo "Removing old $OUTFILE"
	rm $OUTFILE
fi

echo "Starting scanner as a background job with ampersand"
sfdx scanner:run --target "$TARGET_DIR" --outfile $OUTFILE &


echo "// TODO: Auth dev hub, create scratch org, deploy code to scratch org"

sleep 10 # Emulating other tasks with a short sleep time


echo "Checking if scanner finished running"
SCANNER_JOB_INSTANCES=`ps -ef | grep "scanner:run --target" | wc -l | xargs` 

# ps command would always include one line for the grep command and the minimum number we'll get is 1

while [ "$SCANNER_JOB_INSTANCES" -gt "1" ]; do
	echo "Waiting for scanner to complete"
	sleep 5
	SCANNER_JOB_INSTANCES=`ps -ef| grep "scanner:run --target" | wc -l | xargs`
done

echo "Scanner completed"

if [ -f "$OUTFILE" ];then
	echo "// TODO: $OUTFILE parsing logic goes here"
        echo "// Exit with a non-zero code if we decide to break the pipeline"
fi

```

----


**Expanding on theme 2:**
Evaluating scanner results feels like a very subjective process - each team could have their own definition of what their threshold is. One team could consider any rule violation a reason to break the pipeline. Another team could be okay with any number of rule violations as long as they are not sev1. Yet another team may want to compare the report with their previous run and break the pipeline only when the number of violations increase.

This drove us to handle results in an open-ended way - we provide all the relevant information and a few different formats to choose from so that users can customize it the way they like it.

**Comment by yasarshaikh** [comment]
Hi @rmohan20  - Thank you for your effort to provide an alternate solution. However, this is not what I meant to.
If you see the package install command - `sfdx force:package:install`, if you execute this command you get immediate result with an ID for checking the result. 

Also, it provides an option to have sync mode by means of -  `--wait 30`.  It is possible to have it through the extensive script but to keep it more abstract, its best if the command itself handles the additional details. 

on theme 2 part - It is given for more understanding. I'm aware that it shall be handled by respective team who need to have quality metrics defined. So it can be ignored for the implementation.

**Comment by ranekere-sfdc** [comment]
@yasarshaikh the CLI commands you specified interact with an Org (& Salesforce Servers) and hence they are set up to be async. Since the scanner runs locally, we have decided to make it as a synchronous process. For the time being, we do not plan to make it async by default.
