### ISSUE TITLE
[BUG] Scanner ignores API version number

### ISSUE THREAD

**Issue by EricsIssue** [forcedotcom/sfdx-scanner#1694]
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

After running the scanner in VS Code, first error listed was for a "ApexCRUDViolation" which is for "Winter 23 (API Version 56)"; however, my code is for Managed Package that is using a lower version of the API. 
The recommended fix was to add this line
```
<rule ref="category/apex/security.xml/ApexCRUDViolation" /> 
```
 which fixes the issue in VS Code, but when I paste that same line in Salesforce, using the "edit" button on a  class, we get  the error message{
 Error: Compile Error: Unrecognized symbol '"', which is not a valid Apex identifier. at line 52 column 11 
} which prevent us from saving. 
Next we try changing the class version to 56 or even 57 does NOT end this error massage. 
Same for error caused by the "VfCsrf" from version 56, which also has a rule fix but neglects to mention how a page can load without an action to load it. 

How can these rule fixes work in VS Code, but then not be save-able in Salesforce? 

### Output / Logs

force-app\main\default\classes\attendance.cls:56  Validate CRUD permission before SOQL/DML operation Security https://docs.pmd-code.org/pmd-doc-7.6.0/pmd_rules_apex_security.html#apexcrudviolation       
                                                   or enforce user mode   

### Steps To Reproduce

Add this line to a class in Salesforce & click save:
```
<rule ref="category/apex/security.xml/ApexCRUDViolation" /> 
```
Get this error message
Error: Compile Error: Unrecognized symbol '"', which is not a valid Apex identifier. at line ....

Do exact same steps in VS Code, then run scanner to have success. 

### Expected Behavior

At minimum I would expect that any change that the Scanner instruction tell me to make in VS Code, can also be made in Salesforce, so that I can have those changes be part of my app. Especially since Salesforce wants give less then 6 weeks to update my app using new tools & features, rather then checkmarx & dev console. 

If such a rule fix is as simple as adding one line of code & is required, then why not just add the fixes at the source code level on Salesforce's severs, so that we don't need to make any changes? Stop waiting our time.

### Operating System

Windows 11, Salesforce api version 51

### Salesforce CLI Version

latest

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

latest

### Urgency

High

**Comment by jfeingold35** [comment]
@EricsIssue , question: Are you adding the provided code snippet directly to an Apex Class, or are you putting it in a PMD config file?

**Comment by EricsIssue** [comment]
@jfeingold35 I'm adding the rule to the Apex Class & clicking save. Then I run the scanner & issue is fixed. My app just uses trigger, class & pages. so need to edit any other file types.

**Comment by jfeingold35** [comment]
@EricsIssue , can you please post the part of the Apex Class where you've added this line of code? Because as-is, it looks like that would render your code syntactically invalid, which would explain why your Org is rejecting it.

**Comment by EricsIssue** [comment]
@jfeingold35 If the "code syntactically invalid," then why am I able to save the code in VS Code? Salesforce checks if the code is valid on save; therefor, VS Code's salesforce plugin should also validate on save.

**Comment by jfeingold35** [comment]
@EricsIssue , yeah, that's why I'm hoping you can post the part of your code where you actually use that snippet. Seeing it in context will really help us out here.

**Comment by EricsIssue** [comment]
@jfeingold35 Also why is Scanner accepting invalid code & giving me links that tell me to write invalid code? 
My code is part of app on the app exchange since 2012, of which the whole point is to keep others from seeing that code. Its not open source.

**Comment by jfeingold35** [comment]
@EricsIssue , I can't actually figure out whether that's what's happening without _seeing_ your code. Could you please post the code in question so I can actually verify that the problem is what I think it is?

**Comment by jfeingold35** [comment]
@EricsIssue , I understand that there are privacy concerns about your code, but my ability to confirm what the actual problem is is limited without being able to see at least part of it.

**Comment by jfeingold35** [comment]
Can you try replacing the directive you used with `// NOPMD` at the line where the violation is allegedly coming from, or prefixing the entire file in question with the following?
```
@SuppressWarnings('PMD.ApexCrudViolation')
```
Those are the recommended ways to silence a PMD violation in an Apex file. I've never seen a recommendation to put an HTML tag into an Apex file, so I'm curious how that's even working.

**Comment by EricsIssue** [comment]
You can see the instructions for yourself in this below image.
<img width="681" alt="image" src="https://github.com/user-attachments/assets/f3a98d68-02f3-4bb1-8999-d7c4e600cf74">

What is the point of demanding I run this scanner for a Security Review,  if we can just suppress the issues? Is there a way to just suppress all issues so I don't need to do this ever again? My app should be "grandfathered in".
I'm having similar issue with suppressing VfCsrf, where this line works at the top of a Visual force page, it works  in VS Code:
@SuppressWarnings('PMD.VfCsrf')
However, in Salesforce, I get this error message on save:
Error: Content is not allowed in prolog.
Also the action I'm using a search command to load the records for the page, & the instruction that the Scanner gives to fix the issue doesn't give an alternative. 
https://docs.pmd-code.org/pmd-doc-7.6.0/pmd_rules_visualforce_security.html#vfcsrf

I'm surprised  that I'm the first person to notice that the Salesforce VS Code plug in & scanner don't validate code on save nor on run scan. I guess everyone else just suppresses the errors to ensure trust & security:)

**Comment by jfeingold35** [comment]
@EricsIssue , thank you for sharing that information. It looks like you might be misunderstanding the documentation.
The XML tag is how you reference the rule if you're writing your own custom PMD ruleset and want that rule to be included, which isn't what you're trying to do here.
You want to suppress the violation, which you do with the `@SuppressWarnings()` or `// NOPMD` syntax that I described earlier and which is documented [here](https://docs.pmd-code.org/latest/pmd_userdocs_suppressing_warnings.html).

The point of integrating the scanner into Security Review is that it allows you to find issues yourself and fix them quickly instead of needing to involve the Security Team. And it's possible to suppress issues because the scanner isn't perfect and sometimes there are false positives or violations that can't be easily fixed. As such, we have an entire procedure for how to document false positives outlined [here](https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/security_review_false_positives.htm).

Incidentally, the scanner _does_ throw an error for syntactically valid code, as seen in the screenshot below, but that error doesn't appear to be propagating back up to the Extension. Thank you for bringing this to our attention; we will add it to our backlog.
![Screenshot 2024-12-10 at 6 45 06 PM](https://github.com/user-attachments/assets/5a11a29b-6eb4-4aa9-85ef-279c01dfe2a9)

However, in my IDE I see the XML tag clearly flagged as invalid syntax thanks to the Salesforce Extension Pack as shown in this screenshot, so perhaps you might consider installing that to help you.
![Screenshot 2024-12-10 at 6 55 19 PM](https://github.com/user-attachments/assets/a612f38a-b1d3-431e-8f9a-2cd94f90b7f0)

And as the [documentation for the VSCode Code Analyzer Extension indicates](https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/code-analyzer-vs-code-extension.html#use-settings-to-customize-how-code-analyzer-works), you _can_ set the extension to run a scan every time you save a file, which should make things more convenient for you.

**Comment by jfeingold35** [comment]
@EricsIssue , since this is an issue with the VSCode Extension specifically, and not the scanner as a whole (which, as mentioned, _does_ throw an error for invalid syntax), I have created a [new issue on the VSCode Extension repo](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/issues/152), so this can be tracked in the correct location.

**Comment by jfeingold35** [comment]
I'm not sure what you mean when you say that `ApexCRUDViolation` and `VfCsrf` are "for" API Version 56. They were both introduced in PMD 5, which means they're at least 7 years old. They are not new.
If you believe that PMD rules should not apply to your API version, then I suggest that you log a bug against PMD directly, because our team's ability to do anything about that is somewhat limited.

**Comment by jfeingold35** [comment]
And in the meantime, if you believe that these rules should not count against you during Security Review, then you should suppress them using the annotation that I've provided, document them as false positives as described, submit for security review, and sort it out with the Security Team.
