### ISSUE TITLE
Allow scanner:run to fail automated builds

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#171]
As reported by user @davidbrowaeys on Twitter first https://twitter.com/DavidBrowaeys/status/1296796993910484992 the commands are not usable in Automated Builds as scanner:run, unlike similar CLI commands, in other plugins doesn't fail when engine issues are found. 

I think adding such a CLI mode to the command (even make it default) would increase the usefulness of the scanner.

FYI: @rmohan20 please see the details below.

**Comment by davidbrowaeys** [comment]
Hi there, 

I think this is awesome the fact that apex pmd is directly linked to DX, and the way to install it is so simple. Great job guys.
 
So I had a few tests and just one small thing when we run the scanner run in Jenkins pipeline it doesn't seems to fail the build if the scanner detects any high severity vulnerability for example. 

```
sfdx scanner:run --target ./**/*.cls
```
Here is a quick example from Jenkins. 
![image](https://user-images.githubusercontent.com/20630942/91041842-10b28e00-e654-11ea-86d2-5b2bb3c6fd9a.png)

As a workaround I did extend the scanner method by running my own. 
https://github.com/davidbrowaeys/DXB/blob/master/src/commands/dxb/source/scanner.ts
So base on the result of scanner:run it will go through the list of issues and throw an SfdxError if system detect anything with severity 1 OR if you mark a rule as high severity through the command : 
```
sfdx scanner:run --target './**/*.cls' --format json > pmdresult.json
                sfdx dxb:source:scanner --severity 1 -f pmdresult.json -r "AvoidSoqlInLoops,ApexUnitTestClassShouldHaveAsserts,AvoidLogicInTrigger"
```

![image](https://user-images.githubusercontent.com/20630942/91041983-54a59300-e654-11ea-8c36-faf939c8e160.png)

It works well and it fit my purpose for now but would be nice if scanner:run would offer this option natively.

**Comment by rmohan20** [comment]
Hi @rsoesemann and @davidbrowaeys - thanks for your helpful feedback.

Have you tried using the run command with `--format junit` option? Something like this:
`sfdx scanner:run --target ./**/*.cls --format junit`

This should return the error in Junit XML format, which is typically translated by CI/CDs as a blocking failure.
`scanner:run` command supports a few more formats for different usecases. `--help` would show you these options.

Side note on Junit format: we have a known bug with this format that was withholding a few rule violations and this has been fixed internally. The fix should be deployed soon as a part of our minor version update.

Thanks,
Roopa

**Comment by rsoesemann** [comment]
@davidbrowaeys Looks like this is exactly what you need. Can you please check and can confirm that I can close this.

**Comment by davidbrowaeys** [comment]
So I did set format as junit as follow 

```
+ sfdx scanner:run --target ./**/*.cls --format junit
```

My build is still successful though. Am I still missing something ? 

![image](https://user-images.githubusercontent.com/20630942/91095355-914aac00-e69f-11ea-8d6a-41d5d5365c5f.png)

**Comment by rmohan20** [comment]
Checked with my teammate @jfeingold35 - CircleCI and Jenkins need non-zero exit code to treat output as a blocking failure. We've created an internal bug for this issue and will prioritize fixing it. Thanks again for pointing it out.

In the meantime, another work around you could try:

Run `scanner:run` with `--outfile` parameter so that rule violations are redirected to this file.
```
sfdx scanner:run --target ./**/*.cls --format junit --outfile testresults.xml
```

And then check if the testresults.xml file was created. If it exists, return a non-zero exit code:
```
if [ -f ./testresults.xml ]; then
            exit 1
fi
```

**Comment by davidbrowaeys** [comment]
@rmohan20 once this issue is fixed, can you describe how this command should behave? 

Will it throw "exit 0" if anything is detected or only when severity is 1 ? Do you have the exact rules ?

**Comment by rmohan20** [comment]
@davidbrowaeys We are considering a few different ways to handle this scenario. We'll update this issue when have more information.

**Comment by rmohan20** [comment]
I finally have an update to provide.

In 2.1 release, we are adding a new flag (`-v | --violations-cause-error`) that can be used with the `scanner:run` command. This flag would allow users to indicate that they expect a non-zero exit code when scanner detects violations. The actual exit code will be the highest severity of rule violation found.

For example, if the scanner was run with `-v` flag and it detected both sev2 and sev3 rule violations, the exit code would be 2.

The flag should work with all format types. It can't be used with the default `--json` flag since `--json` flag treats non-zero exit codes as real errors and the output JSON cannot include the rule violation information.

**Comment by rsoesemann** [comment]
@davidbrowaeys I will close this for now as I think that is a good solution. Please tell me to reopen if you disagree.

**Comment by Rightback** [comment]
Can we define the severity to which the pipeline should fail. for example if we set the severity to 2 it means any violation greater than 2 once detected should fail the pipeline but if its less than 2 it should pass
