### ISSUE TITLE
@W-8241107@ Specifying "--engine pmd" finds zero violations

### ISSUE THREAD

**Issue by Tzeimi** [forcedotcom/sfdx-scanner#260]
Hello,

After doing some testing with the scanner just found out that the current configuration provided in the path 

~/.sfdx-scanner/Config.json

the ESLint attribute disabled: false, throws errors like the following:

Parsing error unexpected token '@' and Parsing error unexpected token = 
example:

import { LightningElement } from 'lwc';

export default class Hello extends LightningElement {
    greeting = 'World';
}

import { LightningElement, track } from 'lwc';

export default class Hello extends LightningElement {
    @track greeting = 'World';
}

After this, set disabled to true and the ESLint-LWC disabled to false and now is working fine.

Any idea why is this happening?

**Comment by jbartolotta-sfdc** [comment]
@Tzeimi Thanks for the question. The following command will invoke the `eslint-lwc` engine and show you LWC specific errors.

```sfdx scanner:run --target './**/lwc/**/*.js' --engine eslint-lwc --category LWC```

Omitting `--category LWC` will show you all eslint and eslint-lwc violations at once. 

A couple of things to note.

1. Scanning non-LWC Javascript with the `eslint` and `eslint-lwc` engines may return slightly different violations because they use different parsers. The parser used by the `eslint-lwc` engine is slightly more forgiving and doesn't throw as many parsing errors.
2. The eslint-lwc engine is disabled by default and will only run when specified via the `--engine` flag. We are still deciding on which engines will be enabled by default in the 3.x release.

**Comment by Tzeimi** [comment]
@jbartolotta-sfdc 

Thanks a lot for the explanation

**Comment by Tzeimi** [comment]
Just found out that if you try to use 

`sfdx scanner:run project-path --engine pmd,eslint-lwc'` it only works with the JS files but not for any type of apex... my work around was to split the analysis in two:

1. any apex related stuff with 1 stage in the pipeline ignoring all the js (ESLint would break the scan)
2. another stage for all the js files

Thanks again :)

**Comment by jbartolotta-sfdc** [comment]
@Tzeimi thanks for the info. 

You have found a bug when explicitly specifying the `pmd` engine. We will fix this bug and you will be able to run both engines at the same time. Sorry for any inconvenience.

**Comment by Tzeimi** [comment]
@jbartolotta-sfdc thank you and I'm glad to provide feedback

**Comment by pramodgavade** [comment]
@jbartolotta-sfdc - Any updates on ability to use pmd engine explicitly? Thanks in advance.

**Comment by jbartolotta-sfdc** [comment]
@pramodgavade sorry for the delay. We will target this for our Mid-July release.

**Comment by jfeingold35** [comment]
The upcoming 2.10.0 release contains a fix for this bug. Please update to that version when available, and then reopen this record if the issue persists.
