### ISSUE TITLE
How to use it in Jenkins?

### ISSUE THREAD

**Issue by aalazzani** [forcedotcom/sfdx-scanner#303]
I tried executing the command 

sfdx scanner:run --format xml --target "force-app/main/default/classes/**/*.cls"

in Jenkinsfile - to build a jenkins pipeline

and I am getting the error message:

```
›   Warning: scanner:run is not a sfdx command.
Did you mean config:get? [y/n]: 
```

- I already installed the scanner plugin in the server hosting Jenkins (in the very same way I installed SFDX CLI). 
- When I run the command above in the machine terminal it works fine but not in Jenkinsfile.
- I tried adding the command "sfdx plugins:install @salesforce/sfdx-scanner" in the Jenkinsfile to install plugin on the fly. Installation is success when pipeline is built but that did not resolve the issue.
- In Jenkinsfile, standard SFDX CLI commands executes properly but not the SFDX Scanner commands.

**Comment by rmohan20** [comment]
Hi @aalazzani - seems like a good idea to try installing the plugin on the fly.
After running the installation command, can you also check if it is listed as an installed plugin? To do this, you can run:
```
sfdx plugins
```
This should list all the installed plugins.
If the Scanner plugin is not installed, is there internet connectivity when the `jenkinsfile` executes?

**Comment by akshay4570** [comment]
Is the issue resolved? I am facing the same issue and I have used the target as 'force-app'. I am getting a warning like
`WARNING: Target: 'force-app' was not processed by any engines.`

And also @rmohan20 I checked the sfdx plugins and it shows they are installed... Can you help me with that

**Comment by rmohan20** [comment]
@akshay4570 Your warning message looks different from the original issue's message and is indeed generated by `sfdx-scanner`. There's no doubt that the plugin install has been successful for you.

Typically, we see the warning you pasted when the scanner does not find any file types in the given target that match the engine's expected file types. You might want to check if this is what's happening in your case.

Also, to know which file type(s) an engine handles, you can look at the config file generated in `<your_home_dir>/.sfdx-scanner/Config.json`. It would be under the engine's `targetPatterns` value.

If this doesn't help resolve your issue, please create a new issue for us with the actual command you ran as well as all the information requested in the template so that we'll have more context to troubleshoot. Thanks.

**Comment by johnbelosf** [comment]
We've provided feedback - please reopen the issue or create a new one if required
