### ISSUE TITLE
@W-8063535@ Define PMD min severity

### ISSUE THREAD

**Issue by damiendurant** [forcedotcom/sfdx-scanner#308]
Hi,

With PMD executor, it possible to define, through -min cli option, the minimum rule severity that will generate an issue  (https://pmd.github.io/latest/pmd_userdocs_configuring_rules.html)

How to provide this option with sfdx-scanner ?

**Comment by ranekere-sfdc** [comment]
@damiendurant currently we do not have the functionality to support this PMD feature. However, I have created an internal work item to address this in future releases.

**Comment by ranekere-sfdc** [comment]
@W-8063535@

**Comment by rmohan20** [comment]
Hi @damiendurant - in the upcoming 2.10.0 release, we are adding a new flag `--severity-threshold` to `scanner:run` command. This can take a value between 1 and 3 as a parameter. This flag would return with a non-zero exit code when at least one detected rule violation has a severity value equal to or more severe than the given parameter value. A CI/CD system would recognize this non-zero exit code as an error.

This implementation may not be exactly the same as your original feature request since `--severity-threshold` acts on a normalized severity value and not the original PMD violation's severity. This is because every engine that the CLI Scanner supports has a different scale for severity and we need a normalized value to correctly compare them.

Please let us know how this works for you. Thanks.
