### ISSUE TITLE
Support SARIF JSON Format

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#309]
SARIF is an OASIS Standard for static analysis alerts. GitHub support uploading SARIF formatted alerts to their CodeScanning API which allows alerts to be surfaced in the Github UI.

The CLI could enable a flag for outputting reports in SARIF. [Eslint is already supporting it](https://www.npmjs.com/package/eslint.formatter.sarif) and PMD is planning it https://github.com/pmd/pmd/issues/2953.

**Additional context**
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github
https://sarifweb.azurewebsites.net/Validation

**Comment by jbartolotta-sfdc** [comment]
Thanks @rsoesemann we will have a look. 

A note about the CLI Scanner's implementation. It always instructs PMD to output XML. The XML is converted to the format that the user has requested. This is done because the Scanner needs to combine results from multiple engines and also sometimes modifies the results for the sake of consistency. 

We will need to decide if there is enough information in the XML to generate SARIF or if the implementation should request SARIF and merge the SARIF results from the different engines.

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc @rmohan20 just FYI, my team and I are going to contribute SARIF support for PMD as part of https://github.com/pmd/pmd/issues/2953 in the next weeks, so adding this to your Scanner should be simple then as both engines PMD and Eslint (https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif) natively support it.

**Comment by jbartolotta-sfdc** [comment]
> @jbartolotta-sfdc @rmohan20 just FYI, my team and I are going to contribute SARIF support for PMD as part of [pmd/pmd#2953](https://github.com/pmd/pmd/issues/2953) in the next weeks, so adding this to your Scanner should be simple then as both engines PMD and Eslint (https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif) natively support it.

Thanks for the update @rsoesemann

**Comment by rsoesemann** [comment]
@jbartolotta-sfdc @rmohan20 super happy to announce that the SARIF renderer will be part of PMD 6.31 next week.

https://github.com/pmd/pmd/pull/3073

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann we will work on exposing this in the Scanner. Thanks for the update.

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann this has been implemented in https://github.com/forcedotcom/sfdx-scanner/pull/350

We have been trying to strike a balance of avoiding proprietary formats, at the same time we normalize the output from the various engines in order to make them consistent.

It turns out the eslint and PMD sarif differ slightly. There are some naming differences, eslint contains additional properties(`artifacts`, `artifactLocation.artifactLocation`), and eslint does not always include the `invocations` node. 

The PR doesn't use the sarif generated from either tool as input, it was too messy to normalize the results produced by the tools versus generating them from scratch. The Scanner is generating sarif that obeys the schema by combining some of the ideas from the eslint and PMD formats. 

**Differences**
1. rule.properties uses `category` and `severity` instead of `ruleset` and `priority`
2. Location uri is prefixed with `file://` (I think the lack of a file:// prefix is probably a bug in the PMD implementation)

**Additions**
1. Each `result` object has a property `level` with possible values `warning` or `error`  [the level property is defined in the schema here](https://docs.oasis-open.org/sarif/sarif/v2.0/csprd02/sarif-v2.0-csprd02.html#_Toc10127839) The PR considers a violation of priority=1 to be an error, and everything else is an warning.
    
Let me know your thoughts.

**Comment by rsoesemann** [comment]
Great to hear about such progress. Will look into this more detailed. Do you think we could improve your situation by adjusting the pmd implementation of SARIF? We are open to that, right @mmoyaferrer?

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann I think we would continue to create the sarif in the Scanner, even if the formats matched. There are at least a couple of reasons for this. 

1. The code required to undo the differences in the eslint output is about the same complexity as generating the sarif from scratch
2. The scanner needs to generate sarif for `retire-js` and engines that we may add in the future. The same code is reused to generate sarif for all engines, having duplicate paths complicates the implementation

**Comment by jbartolotta-sfdc** [comment]
@rsoesemann This was released as part of 2.6. Please let us know if you have any feedback on it.

**Comment by jbartolotta-sfdc** [comment]
@k11eran This is the repository of the Salesforce CLI Scanner. The CLI Scanner aggregates multiple engines including PMD. It appears that you are using PMD directly. The best place to get help for your issue would be at the PMD repo which can be found here. https://github.com/pmd/pmd 

In case it helps. I was able to run the PMD command directly by invoking with the following syntax on Linux
```bash
> pmd-bin-6.32.0/bin/run.sh pmd -l apex -R category/apex/security.xml -d test/code-fixtures/apex -format sarif
```

**Comment by k11eran** [comment]
Got it working in Linux. Thanks for the help. :)
