### ISSUE TITLE
Code Scanner not working on Windows

### ISSUE THREAD

**Issue by udeprezzot** [forcedotcom/sfdx-scanner#417]
Hi Team,
I have recently installed the Code Scanner CLI on Window laptop, I got this error:

editions-autoloader-none-broadened] Error Plugin: sfdx-cli: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.

Any suggestion?

**Comment by jbartolotta-sfdc** [comment]
@udeprezzot sorry for any inconvenience. This was an issue that appeared in versions `2.6`-`2.8` of the plugin. 

You can fix the issue by executing the following commands to upgrade your plugin

```bash
> sfdx plugins:uninstall @salesforce/sfdx-scanner
> sfdx plugins:install @salesforce/sfdx-scanner
```

More information on the underlying cause is contained in this issue https://github.com/forcedotcom/sfdx-scanner/issues/412 

Let us know if you still have trouble after upgrading.

**Comment by udeprezzot** [comment]
Many Thanks! It works!

**Comment by udeprezzot** [comment]
closed with resolution
