### ISSUE TITLE
Consider @param with type and name

### ISSUE THREAD

**Issue by jvaloto** [forcedotcom/sfdx-scanner#421]
Hello,

When we use **_@param_** with type and parameter name the document don't count this @param and causes a _Violation Sev3_.

The same is happening when use inner class:
**_@param VisualEditor.DesignTimePageContext context_**

example:

![image](https://user-images.githubusercontent.com/41273708/122961828-28819e00-d35b-11eb-8775-30dfb6b3d659.png)

![image](https://user-images.githubusercontent.com/41273708/122962652-03415f80-d35c-11eb-88d4-c99cfd210197.png)

This change is possible?

**Comment by rmohan20** [comment]
Hi @jvaloto - thanks for reaching out.

ApexDoc expects the variable name right after the `@param` annotation in the comment. The type name isn't valid in the position of the variable, which is why the rule throws a violation. If you had to indicate the type, how about putting it in the description of the param? For example:
```
/**
  * @description return param a + param b
  * @param a an integer value
  * @param b another integer value
  * @return String
  **/
```
This way the comment continues to be in the expected format.

**Comment by jvaloto** [comment]
Hello @rmohan20

I'll start to use like you said.

Thanks!
