### ISSUE TITLE
without sharing

### ISSUE THREAD

**Issue by JoselitoOgalesco** [forcedotcom/sfdx-scanner#956]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Scanner Version [e.g. 22]

**Additional context**

"Workaround": Have you found any ways to sidestep the problem?

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".

**Comment by JoselitoOgalesco** [comment]
I tried to scan my apex class that has "without sharing" but the result didn't about the validation. 

sfdx scanner:run --target "force-app" --category "Security" --outfile "./scanner_out.html" --format "html"

**Comment by johnbelosf** [comment]
@JoselitoOgalesco can you please fill in the bug template and provide more details? This bug was opened without any details. Thank you:

---

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS]
Scanner Version [e.g. 22]
Additional context
Add any other context about the problem here.

"Workaround": Have you found any ways to sidestep the problem?

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".

**Comment by johnbelosf** [comment]
@JoselitoOgalesco I am going to close this for now, please open a new issue and fill in the bug template and we will look into it.
