### ISSUE TITLE
[Feature Request] Overview of Engines available

### ISSUE THREAD

**Issue by DougMidgley** [forcedotcom/sfdx-scanner#993]
**Is your feature request related to a problem? Please describe.**
There is no authoritative view of all engines which can be run and what they do.

**Describe the solution you'd like**
Update documentation to show available engines and what they do

**Describe alternatives you've considered**
Trial and Error based on issues/existing documentation

**Additional context**

"Workaround":  No real work around

"Urgency": Not urgent, just would help understand value

**Comment by johnbelosf** [comment]
Thanks for this @DougMidgley - Currently you can see that we have a dedicated page for each engine under "Architecture" in our [docs](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/architecture/architecture/)

We'll use this item to add additional detail to this page so that we have a comprehensive list in this page too

**Comment by DougMidgley** [comment]
Hey @johnbelosf , ah didnt notice this page! thanks!
